sudo: false

dist: trusty

language: python

python: '3.6'

script:
  - pip install flake8
  - flake8 .

after_success:
  - ./generate_readme.py > README.md
  - ./.travis_push.sh

branches:
  only:
    - master
