sudo: false

dist: trusty

language: python

python: '3.6'

script:
  - pip install flake8
  - flake8 .
  - ./run_tests.py

after_success:
  - |
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      ./generate_readme.py > README.md
      ./.travis_push.sh
    fi

branches:
  only:
    - master
